whitelist_rules:
    # rules
    - anyobject_protocol
    - array_init
    - class_delegate_protocol
    - compiler_protocol_init
    - convenience_type
    - cyclomatic_complexity
    - deployment_target
    - discouraged_direct_init
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - duplicate_enum_cases
    - duplicate_imports
    - dynamic_inline
    - empty_xctest_method
    - explicit_init
    - fatal_error_message
    - file_name
    - for_where
    - force_cast
    - force_try
    - force_unwrapping
    - function_default_parameter_at_end
    - function_parameter_count
    - identical_operands
    - implicitly_unwrapped_optional
    - large_tuple
    - legacy_constant
    - legacy_constructor
    - legacy_hashing
    - legacy_multiple
    - line_length
    - mark
    #- missing_docs
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords
    - private_action
    - private_outlet
    - protocol_property_accessors_order
    - redundant_nil_coalescing
    - redundant_objc_attribute
    - redundant_optional_initialization
    - redundant_set_access_control
    - redundant_type_annotation
    - redundant_void_return
    - strong_iboutlet
    - trailing_semicolon
    - type_body_length
    - type_name
    - unneeded_break_in_switch
    - unused_capture_list
    - unused_closure_parameter
    - weak_delegate
    - xct_specific_matcher
    - xctfail_message
    - yoda_condition

    # style rules
    - attributes
    - closing_brace
    - closure_end_indentation
    - closure_parameter_position
    - closure_spacing
    - collection_alignment
    - colon
    - comma
    - control_statement
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - file_header
    - identifier_name
    - implicit_getter
    - implicit_return
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_nsgeometry_functions
    - legacy_random
    - let_var_whitespace
    - literal_expression_end_indentation
    - multiline_arguments
    #- multiline_arguments_brackets
    - multiline_literal_brackets
    - multiline_parameters
    #- multiline_parameters_brackets
    #- multiple_closures_with_trailing_closure
    - opening_brace
    - operator_usage_whitespace
    - redundant_discardable_let
    - return_arrow_whitespace
    - sorted_imports
    - statement_position
    - switch_case_alignment
    - todo
    - toggle_bool
    - trailing_closure
    - trailing_newline
    - unneeded_parentheses_in_closure_argument
    - unused_optional_binding
    - vertical_parameter_alignment
    - vertical_whitespace
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - void_return

    # performance
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - empty_count
    - empty_string
    - first_where
    - is_disjoint
    - last_where
    - modifier_order
    - reduce_boolean
    - sorted_first_last
    - trailing_whitespace
    
excluded:
    - Pods
    - DerivedData
    - TestingCoordinatorNavigationTests
    - Wiremock
    
    - Login/Tests
    - Register/Tests
    - Navigation/Tests

function_parameter_count:
    - 4 # warning
    - 5 # error
    
identifier_name:
    min_length:
        error: 2
        
large_tuple: 4
        
line_length: 120

type_body_length:
    - 300 # warning
    - 400 # error
    
type_name:
  allowed_symbols: "_"

trailing_closure:
  only_single_muted_parameter: true

force_cast: error
force_try: error
weak_delegate: error
contains_over_filter_count: error
contains_over_filter_is_empty: error
contains_over_first_not_nil: error
empty_count: error
empty_string: error
first_where: error
is_disjoint: error
last_where: error
reduce_boolean: error
sorted_first_last: error
trailing_whitespace: error

reporter: "xcode"